export const environment = {
  production: false,
  backend: 'http://localhost:9090',
  ROLE_PERSONNE: 'ROLE_PERSONNE',
  ROLE_DEMANDEUR: 'ROLE_DEMANDEUR',
  ROLE_GESTIONNAIRE: 'ROLE_GESTIONNAIRE',
  ROLE_VALIDATEUR: 'ROLE_VALIDATEUR',
  ROLE_ADMIN: 'ROLE_ADMIN',
  ROLE_AUDITEUR: 'ROLE_AUDITEUR',
};