package com.bollore.stockbolloreback.enumeration;

public enum EnumProduitStatus {
    EN_STOCK,
    EN_UTILISAION,
    MISE_AU_REBUT,
    EN_REPARATION,

    EN_ATTENTE_VALIDATION,
    EN_ATTENTE_DE_MISE_AU_REBUT,
    EN_ATTENTE_ENVOIE_REPARATION,

    EN_ATTENTE_LIVRAISON,
    EN_ATTENTE_LIVRAISON_REP,
    EN_ATTENTE_LIVRAISON_REB,

    EN_ATTENTE_SORTIE_MAG_REB,
    EN_ATTENTE_SORTIE_MAG_REP,
    EN_ATTENTE_SORTIE_MAG_STA,

    EN_ATTENTE_RECEPTION_STA,
    EN_ATTENTE_RECEPTION_REB,
    EN_ATTENTE_RECEPTION_REP,
    
    
    EN_ATTENTE_DE_RETOUR,
}
